[book]
title = "Rust Con Ejemplos"
description = "Rust con ejemplos (Rust by Example, RBE) es una colección de ejemplos ejecutables que ilustran varios conceptos de Rust y librerias estándar."
author = "The Rust Community"
language = "es"

[output.html]
additional-css = ["custom.css"]

[output.html.playpen]
editable = true
editor = "ace"

[output.html.fold]
enable = true
